### ISSUE TITLE
I only see POST & OPTION

### ISSUE THREAD

**Issue by eikebartels** [yunojuno/django-request-profiler#25]
Hello, 

I only see POST & OPTION requests 

![image](https://user-images.githubusercontent.com/767979/73862877-77e72d00-483f-11ea-8f80-b5d22df68686.png)

My filter is the default: 

![image](https://user-images.githubusercontent.com/767979/73862904-86354900-483f-11ea-8b67-2aaafebf0f01.png)

Do I do something wrong? 

Note: I'm using the Django rest framework

**Comment by hugorodgerbrown** [comment]
@eikebartels did you get to the bottom of this?
